services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: contactsidentitydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    environment:
      KEYCLOAK_DB: postgres
      KEYCLOAK_DB_URL: jdbc:postgresql://postgres-db:5432/contactsidentitydb
      KEYCLOAK_DB_USERNAME: admin
      KEYCLOAK_DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: token-exchange,authorization
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    command:
      - start-dev

  seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

volumes:
  postgres_data:
